Replace the 'new collective' form with a modal
nextcloud/collectives pull request #504
Opened 2023-01-12 12:42 UTC by mejo-

### 📝 Summary

* Allows to create a new collective (optionally using an existing circle)
* Allows to select members while creating a collective.
* Resolves: #464

#### 🖼️ Screenshots

![grafik](https://user-images.githubusercontent.com/3582805/212067115-de57d4b6-6450-4d45-9eda-239935b66568.png)

![grafik](https://user-images.githubusercontent.com/3582805/212067258-378ce9af-bfce-43fc-8ed5-398ba2bcb6e1.png)

![grafik](https://user-images.githubusercontent.com/3582805/212067460-123e168e-fb6c-4dcf-8fe2-f1bae177961f.png)

#### Screencast

[recording1.webm](https://user-images.githubusercontent.com/3582805/212068549-a0bc1849-3b2a-4401-8534-77eee36ebc9a.webm)

### 🚧 TODO

- [ ] Fix cropped bottom in member suggestions
- [ ] Finish `ADD_MEMBER_TO_CIRCLE` in `store/circles.js`
- [ ] Cypress tests

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/collectives/blob/main/README.md) or [documentation](https://github.com/nextcloud/collectives/blob/main/docs/)) has been updated or is not required

2023-01-12 12:52 UTC, juliushaertl commented on cypress/e2e/pages.spec.js
> +		it.only('Allows to display/close TOC and switch page modes in between', function() {
```suggestion
		it('Allows to display/close TOC and switch page modes in between', function() {
```

2023-01-12 12:54 UTC, mejo- commented on cypress/e2e/pages.spec.js
> +		it.only('Allows to display/close TOC and switch page modes in between', function() {
Haha, nice catch. Fixed now :blush:

2023-01-12 15:04 UTC, jancborchardt submitted a review, later dismissed
Looks very nice, very much like in Talk :) cc @marcoambrosini. 2 pieces of feedback:
- [ ] Also like in Talk, in the first step we could already list some permissions, e.g. the editing and sharing permissions, as well as the default page mode? Then it’s not so empty, and the permissions are set before anything is shared, very secure.
- [ ] The "Collective with that name already exists" could already be shown in the name input step, no? (Like how web services often check in the background if the account name is still available.)

2023-01-12 16:03 UTC, nimishavijay requested changes
Super nice! Flow looks really great :) Agreed with @jancborchardt plus some points from my side:

- [ ] The icon for selecting a circle seems unclear. Maybe it could a button with a label "Choose circle" or something like that?
- [ ] "Select members" --> "Add people"? cc @jancborchardt on this one
- [ ] It also seems like it's confusing to create a personal collective. We could possibly add a secondary button on the left of "Select members" which says "Create" or something. also cc @jancborchardt 
- [ ] Hover feedback for the emoji seems to be a few pixels too wide, it should be a circle (equal width and height)
- [ ] Each item in the list of users doesn't need to have a background, background shown only on hover and select would work better :)
- [ ] The checkmark could have more margin all around. Even better: Align all checkmarks to the right, similar to creating a new group conversation in Talk 
![image](https://user-images.githubusercontent.com/52440189/212115994-06c89a70-1c87-419a-8df8-dba43ba1d19e.png)
- [ ] Also a question: what is the symbol in the search field on the right? 
![image](https://user-images.githubusercontent.com/52440189/212112473-be1c7a02-f2af-4073-9121-29af405f4292.png)

2023-01-12 16:50 UTC, julien-nc commented
Wow that looks very nice! :star_struck: 

* [ ] The bottom right button looks the same when you can't click it (for example "Select members" is disabled when no collective name was entered yet) and when something is loading (for example "Create" is disabled when attempting to create the collective). There could be a loading icon in the button's icon template while creating.
* [ ] There could be an empty content while choosing the collective name, there seems to be one only while choosing the members. The empty content icon could be the app icon and the title could be something like "Enter the new collective name". The icon alone without title would be fine too.

2023-02-14 13:22 UTC, mejo- commented
> * [ ]  Also like in Talk, in the first step we could already list some permissions, e.g. the editing and sharing permissions, as well as the default page mode? Then it’s not so empty, and the permissions are set before anything is shared, very secure.

In the long run I thought that we could provide templates for the new collective here. That's why I kept it empty for now. Sure, we could add settings there, but I'd like to do this in a follow-up if at all, as it requires quite a bit of extra work.

>     * [ ]  The "Collective with that name already exists" could already be shown in the name input step, no? (Like how web services often check in the background if the account name is still available.)

Yeah, that would be a nice user experience. On the other hand, that would require an API call to check if a circle with a specifici name exists (circle names are global on the instance) and that would mean to allow enumeration. At the moment, when creating a collective, the backend tries to create the circle and errors out if it already exists. That's way harder to brute-force than an API that allows to check if a name is taken.

2023-02-14 14:38 UTC, mejo- commented
>  Also a question: what is the symbol in the search field on the right?

Hehe, that's my password manager :wink:

2023-02-15 14:17 UTC, mejo- commented
@nimishavijay @jancborchardt @julien-nc I tried to address all your feedback, thanks a lot. Some ideas I didn't implement, but I commented on them instead, see above. Screenshots and screencast above are updated as well.

2023-02-15 14:46 UTC, susnux commented
Looks really nice!
I will look into this later, but from a quick look on the code: Is there a special reason for not using the `NcSelect` component for the member picker? I think it would simplify the code a lot.

2023-02-15 15:14 UTC, mejo- commented
> Looks really nice! I will look into this later, but from a quick look on the code: Is there a special reason for not using the `NcSelect` component for the member picker? I think it would simplify the code a lot.

Thanks for looking into it @susnux! The main reason is that the member picker dialog should look similar to how it looks in Talk when creating a new conversation and in Contacts when picking members for a circle. I agree that we should streamline this into a nextcloud-vue component at some point.

2023-02-20 16:05 UTC, max-nextcloud approved these changes
Just had a look at the code so far.
Looks good to me. :tada: 
Just some minor comments.

2023-02-20 16:05 UTC, max-nextcloud commented on src/components/Nav/NewCollectiveModal.vue
> +			return null
If you don't return anything `undefined` will be returned - which should be just as good as null here.

```suggestion
```

2023-02-20 16:53 UTC, nimishavijay approved these changes
Looks great! Only point I noticed is the button for choosing a circle is a bit confusing without a label, but we can merge this now and open a follow up issue about it :)

2023-02-21 11:46 UTC, mejo- commented on src/components/Member/MemberPicker.vue
> +						:title="t('collectives', 'Remove {type} {name}', { type: member.type, name: member.label })"
Agreed, good catch :ok_hand:

2023-02-21 11:49 UTC, mejo- commented on src/components/Member/MemberPicker.vue
> +			data.exact = [] // removing exact from general results
Uh nice, much better :heart:

2023-02-21 11:52 UTC, mejo- commented on src/components/Member/MemberPicker.vue
> +				.sort((a, b) => a.shareType - b.shareType)
Agreed.

2023-02-21 13:41 UTC, mejo- commented on src/components/Member/MemberPicker.vue
> +				}
This turned out to be rather dead code (leftover from an earlier implementation). The current results don't have a `displayName` at all, their `label` attribute is used. And given that we already group results by user, circle and group, I don't think that we have to take extra measures to distinguish them further. At least not for now.

2023-02-21 14:16 UTC, merged