Fix visual glitches
nextcloud/collectives pull request #896
Opened 2023-09-21 14:47 UTC by mejo-

### 📝 Summary

* Resolves: #831 

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

2023-09-21 17:39 UTC, max-nextcloud commented
Now the background is primary for me in the sidebar but the font color is black:
![grafik](https://github.com/nextcloud/collectives/assets/97337118/7c514d4e-4dc1-4c1f-ae1a-07e8f91d3ddc)

Looking at how other apps (talk, contacts) handle this the selected element in the navigation has a slighly brighter background and black font ( in bright mode).

![grafik](https://github.com/nextcloud/collectives/assets/97337118/2d01aed7-28ec-4147-be5f-5a4a83c75d5e)

2023-09-21 17:40 UTC, max-nextcloud requested changes
Please fix the App Navigation colors. I think they should match what other apps do or at least combine primary with white color.

2023-09-25 10:39 UTC, mejo- commented
> Please fix the App Navigation colors. I think they should match what other apps do or at least combine primary with white color.

Agreed. Actually the issue reported here got already fixed in `@nextcloud/vue`, so no need for further custom fixes on our side. Removed the corresponding change from this PR.

2023-09-25 11:20 UTC, max-nextcloud approved these changes

2023-09-25 12:05 UTC, merged